string mode # 'random' or 'fixed'
uint8 type_of_point # 1 for pick, 2 for place
bool on_object # True if we want a point ON an object
uint16 crop_width
uint16 crop_height
uint16 x # In case of 'fixed', the (x,y) pixel coordinates
uint16 y
---
sensor_msgs/Image rgb_crop
sensor_msgs/Image depth_crop
uint16 x_pixel # Coordinates in image frame (pixel)
uint16 y_pixel
uint16 x_robot # Coordinates in robot frame (meter)
uint16 y_robot
uint16 z_robot
